module.exports = {
  compact: true,
  controlFlowFlattening: true,
  controlFlowFlatteningThreshold: 0.75,
  deadCodeInjection: true,
  deadCodeInjectionThreshold: 0.4,
  debugProtection: true,
  debugProtectionInterval: 2000,
  disableConsoleOutput: true,
  identifierNamesGenerator: 'hexadecimal',
  log: false,
  numbersToExpressions: true,
  renameGlobals: false,
  selfDefending: true,
  simplify: true,
  splitStrings: true,
  splitStringsChunkLength: 10,
  stringArray: true,
  stringArrayEncoding: ['base64'],
  stringArrayThreshold: 0.75,
  transformObjectKeys: true,
  unicodeEscapeSequence: false,
  
  // TypeScript and JSX support
  target: 'browser',
  sourceMap: false,
  sourceMapMode: 'separate',
  sourceMapSourcesMode: 'sources-content',
  
  // React Native specific settings
  reservedStrings: [
    'react',
    'react-native',
    'expo',
    'navigation',
    'asyncstorage',
    'clipboard',
    'cookies',
    'picker',
    'vector-icons',
    'paper',
    'qrcode',
    'randombytes',
    'reanimated',
    'safe-area',
    'screens',
    'svg',
    'webview',
    'bip39',
    'bs58',
    'buffer',
    'ethers',
    'tweetnacl',
    'axios',
    'form',
    'gesture',
    'haptics',
    'image',
    'linking',
    'router',
    'splash',
    'status-bar',
    'symbols',
    'system-ui',
    'web-browser',
    'process',
    'readable-stream',
    'text-encoding',
    'url',
    'util'
  ],
  
  // Exclude certain files/folders from obfuscation
  exclude: [
    'node_modules/**',
    'android/**',
    'ios/**',
    'assets/**',
    '*.config.js',
    '*.config.ts',
    'metro.config.js',
    'babel.config.js',
    'tsconfig.json',
    'package.json',
    'app.json',
    'eas.json'
  ]
}; 